export const ELEMENTS = {
    screenTitle: '#root >  div > div > div > h2',
    etContractName: 'input[name="name"]',
    etJobTitle: 'input[name="jobTitle"]',
    selectElement: '.select__control',
    seniorSeniority: '#react-select-2-option-3',
    selectedOption: '.select__single-value',
    ddArrow: 'div[direction="up"]',
    optionsScope: 'div[class="scope-box"]',
    datePicker: 'div[name="effectiveDate"]',
    currentDay: '.react-calendar__tile--active > abbr',
    calendar: '.react-calendar__month-view__days',
    btnPreviousMonth: 'button[class~="react-calendar__navigation__prev-button"]',
    btnSubmit: 'button[type="submit"]',
    etRate: 'input[name="rate"]',
    btnSpecialClause: 'div[data-qa="special-clause-card"] > div > div:nth-child(2) > button',
    textBoxSpecialClause: 'div[data-qa="special-clause-card"] > * textarea',
    nextBtn: '.mt-7 > button',
    selectCountry: 'div[data-qa="contractor-tax-residence"] > * div[class~="select"]',
    selectState: 'div[data-qa="contractor-tax-residence-province"] > * div[class~="select"]',
    contractType: 'div[data-qa="contract-type"] > h4',
    contractStartDate: 'div[data-qa="contractors-start-date"] > * div',
    contractRate: 'div[data-qa="rate"] > h4',
    contractPeriod: 'div[data-qa="rate"] > h4 > div',
    contractCountry: 'div[data-qa="contractors-country"] > h4',
    contractSpecialClause: 'div[data-qa="dpa-row-special-clause-value"]  > div[class="pre-wrap"]',
}